# Generated by Django 4.1 on 2022-08-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0003_alter_documento_pertence_a"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="arquivo",
            field=models.FileField(default="", upload_to="documentos"),
            preserve_default=False,
        ),
    ]
